### ISSUE TITLE
 'StateVector' object has no attribute 'heading'

### ISSUE THREAD

**Issue by makrsmark** [Jxck-S/plane-notify#73]
same as #42 caused by regression in 823d280965746153ac2e47bb052b5c5d5e58f59a
